Add alert rule for juju machines being down
canonical/charm-prometheus-juju-exporter pull request #26
Opened 2023-03-16 07:52 UTC by sudeephb

2023-03-16 08:12 UTC, rgildein reviewed
Can you provide description to this PR + add some example how did you tested this. Thanks

2023-03-17 09:54 UTC, Pjack reviewed
It's an interesting way to detect the warning message. In the traditional way, we will setup a clear threshold for the number of machines. So the warning will be always there until the number come back to normal. 

But following by this logic, the warning may disappear after 1 hour, is that correct?  Because after 1 hour, the comparison result will be the same even the number is incorrect.

2023-03-17 12:20 UTC, rgildein approved these changes
To me this looks good, but I have no experience with alert rules. So I think someone else could review it.

2023-03-20 09:54 UTC, sudeephb commented
> It's an interesting way to detect the warning message. In the traditional way, we will setup a clear threshold for the number of machines. So the warning will be always there until the number come back to normal.
> But following by this logic, the warning may disappear after 1 hour, is that correct? Because after 1 hour, the comparison result will be the same even the number is incorrect.

Yes, the alert will disappear in an hour. The idea behind this alert is to detect if the machines go down during smooth running of the cloud. The alert being fired for 1 hour should be enough to inform the operator that this has occurred. In cases where this is expected(planned down scaling, maintenance, etc), the operator can mute/ignore the alerts on the receiver end(Pagerduty).
Also, we don't know what the 'correct' number is. So, if we keep it on for too long, the alert will keep firing even when the machines are scaled down intentionally.

2023-03-21 14:55 UTC, agileshaw requested changes
This current approach would trigger the alert rule in two scenarios:
1. one or more juju machine agent(s) down
2. one or more juju machines removed when downsizing a cloud

After discussion w/ @przemeklal , firing alerts in the second scenario is not desirable. Hence, alerting on something like `count(juju_machine_state == 0) > 0` would be more appropriate. With a static threshold, we also prevent the alert from disappearing after a time period as mentioned by @Pjack.

2023-03-23 18:23 UTC, aieri approved these changes
lgtm

2023-03-24 09:25 UTC, mkalcok commented
This one racked up enough approvals and since it matches with requests from Bootstack, I'm gonna merge it.

2023-03-24 09:25 UTC, merged