Pin ops version to support bionic deployments
canonical/charm-prometheus-juju-exporter pull request #31
Opened 2023-03-17 20:12 UTC by agileshaw

2023-03-17 21:26 UTC, aieri requested changes
Can we add a functional test run on bionic? I see we are already testing focal and jammy

2023-03-17 21:38 UTC, agileshaw reviewed
recheck

2023-03-17 22:20 UTC, agileshaw commented
> Can we add a functional test run on bionic? I see we are already testing focal and jammy

@aieri Great suggestion. I've added bionic bundle and the CI has passed (https://github.com/canonical/charm-prometheus-juju-exporter/actions/runs/4451800736/jobs/7818876921?pr=31).

2023-03-17 22:36 UTC, aieri approved these changes

2023-03-18 00:31 UTC, mkalcok approved these changes

2023-03-20 08:38 UTC, merged